version: '3.2'

services:
  api:
    image: gcr.io/anthive-prod/api:latest #your image with api running on port :8080
    env_file:
      - ./api.env
    ports:
      - "8080:8080"
    networks:
      - elk
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
